language: python
matrix:
  include:
  - os: linux
    python: 3.6
    env: TOXENV=py36
  - os: linux
    python: 3.5
    env: TOXENV=py35
  - os: linux
    python: 3.4
    env: TOXENV=py34
  - os: linux
    python: 3.3
    env: TOXENV=py33
  - os: linux
    python: 2.7
    env: TOXENV=py27
  - os: osx
    language: generic
    env: 
      - PYTHON='3.6.2'
      - TOXENV=py36
  - os: osx
    language: generic
    env:
      - PYTHON='3.5.2'
      - TOXENV=py35
  - os: osx
    language: generic
    env:
      - PYTHON='3.4.6'
      - TOXENV=py34
  - os: osx
    language: generic
    env:
      - PYTHON='3.3.6'
      - TOXENV=py33
  - os: osx
    language: generic
    env: 
      - PYTHON='2.7.13'
      - TOXENV=py27
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
         PRE_CMD=linux32

branches:
  only:
    - master
    - /^\d\.[\d.]+$/

before_install:
- |
  if [[ $PYTHON && "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update;
    brew install openssl readline;
    brew outdated pyenv || brew upgrade pyenv;
    brew install pyenv-virtualenv;
    pyenv install $PYTHON;
    export PYENV_VERSION=$PYTHON;
    export PATH="/Users/travis/.pyenv/shims:${PATH}";
    pyenv-virtualenv venv;
    source venv/bin/activate;
    python --version;
  fi;
  echo [distutils]                                  > ~/.pypirc;
  echo index-servers=pypi                          >> ~/.pypirc;
  echo [pypi]                                      >> ~/.pypirc;
  echo username=kmike                              >> ~/.pypirc;
  echo password=$PYPIPASSWORD                      >> ~/.pypirc;
  touch .travis_tag;
  if [[ $DOCKER_IMAGE ]]; then
    echo $TRAVIS_TAG > .travis_tag;
    cat ~/.pypirc > .pypirc;
  fi;

install:
- |
  if [[ $DOCKER_IMAGE ]]; then
    docker pull $DOCKER_IMAGE &&
    docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.manylinux-install.sh;
    exit;
  else
    pip install --upgrade pip;
    pip install -r requirements-doc.txt;
    pip install tox;
    pip install -U cython;
  fi;

script:
- ./update_cpp.sh
- tox

after_success:
- pip install wheel twine 
- if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then
  python -W ignore setup.py bdist_wheel;
  twine upload dist/*;
  fi;
- if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "linux" ]]; then
  python -W ignore setup.py sdist;
  twine upload dist/*;
  fi;

env:
  global:
    - secure: HQDMJlzbWMSuA2YANijtacm9croR5e9BTSKq08QDp1Fc33BGLjDWXeKPOcZSx3LR9AdCN9CLA2NQn3hQ8wViibrCmn5kUFdzIDxpFgPrq5fvOTU43Kf8o/DbDZxK2Loqw7LwskwxTpJZOnp2gwF6kNJiC4hygI9HID8qqs9l480=
